diode/config/routes.rb
Diode::Application.routes.draw do
  get "settings/index"

  get "settings/password"

  get "settings/iquit"

  resources :tags, :settings

  resources :jokes do
    resources :comments
  end
  
  devise_for :users

  get "home/index"
  root :to => 'home#index'
  match 'home/:user_id' => 'home#show', :as => :show
  match 'home/:user_id/jokes' => 'home#show_user_jokes', :as => :show_user_jokes
  
  resources :users do
      member do
        get :following, :followers
      end
  end
  
  resources :relationships, :only => [:create, :destroy]
    

end

diode/app/views/layouts/_fav_touch.html.erb
<!-- Le fav and touch icons -->
<link rel="shortcut icon" href="images/favicon.ico">
<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

diode/app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
<script type="text/javascript">
	$(document).ready(function () {
		$('.alert-message').alert();
	})
</script>
<div class="alert-message block-message info fade in" style="
position: relative;
top:-20px;
left: 0;
right: 0;
overflow: visible;
padding-top:0px;
padding-bottom:0px;">
  <a class="close" href="#">×</a>
  <p style="text-align:center;"><strong><%=flash[:notice]%></strong> </p>
</div>
<% end %>

diode/app/views/layouts/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id),
    :remote=>true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "关注",:class=>"btn success" %>
<% end %>

diode/app/views/layouts/_follow_form.html.erb
<% if current_user != @user %>
  <div style="text-align:center;" id="follow_form"><!--follow-->
  <% if current_user.following?(@user) %>
    <%= render :partial => 'layouts/unfollow' %>
  <% else %>
    <%= render :partial => 'layouts/follow' %>
  <% end %>
  <!--/follow--></div>
<% end %>

diode/app/views/layouts/_footer.html.erb
<footer>
     <p>&copy; Company 2011</p>
</footer>

diode/app/views/layouts/_sidebar.html.erb
<div class="sidebar">
   <div class="well">
     <h5>热门作者</h5>
     <ul>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
     </ul>
     <h5>热门标签</h5>
     <ul>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
     </ul>
     <h5>友情链接</h5>
     <ul>
       <li><a href="#">Link</a></li>
       <li><a href="#">Link</a></li>
     </ul>
　　　　　　　　　<h5><a href="#">关于本站</a></h5>
     
   </div>
 </div>

diode/app/views/layouts/_topbar.html.erb
<div class="topbar">
      <div class="topbar-inner">
        <div class="container-fluid">
          <%= link_to '段子社区',root_path, :class=>'brand' %>
          <ul class="nav">
            <li class="active"><%= link_to '首页',root_path%></li>
            <li><a href="#about">最新</a></li>
            <li><a href="#contact">24小时最热</a></li>
            <li><a href="#contact">本周最热</a></li>
            <li><a href="#contact">本月最热</a></li>
            <li><a href="#contact">本年最热</a></li>
          </ul>
          <p class="pull-right">
            <% if user_signed_in? -%> <!-- Provided by devise -->
                <%= link_to image_tag("msg.png",:size=>"24x24",:class=>"header_msg"), 'http://placehold.it/24x24', :title=> "连接新浪" %>
                <%= current_user.email %> |
                <%= link_to '我的主页', user_path(current_user) %> |
                <%= link_to '账号设置', settings_index_path %> |
                <%= link_to '退出登陆', destroy_user_session_path, :method => :delete %> | 
                <%= link_to '讲一个', new_joke_path %> 
                <!-- 
                <%= link_to image_tag("msg.png"), '/auth/tsina', :title=> "连接新浪" %>
                -->
            <% end %>
            <% unless user_signed_in? -%>
                <%= link_to '注册', new_user_registration_path %> |
                <%= link_to '登录', new_user_session_path %>
            <% end %>
            </p>
        </div>
      </div>
   </div>

diode/app/views/layouts/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
             :remote=>true, :html => { :method => :delete } do |f| %>
  <button class="btn success disabled">已关注</button> | <%= f.submit "取消关注",:class=>"btn danger" %>
<% end %>

diode/app/views/layouts/_user_stat.html.erb
<% @user ||= current_user %>
<div style="text-align:center;"><!--个人信息-->
	<dl>
		<dt><a href="" title="haojii"><img src="http://placehold.it/128x128"></a></dt>
		<dd>
		<a href="#"><%= @user.email %></a>
		<p>签名档</p>
		</dd>
	</dl>
	<ul class="unstyled">	
		<li><span>段子:</span><strong><%= @user.jokes.count %></strong></li>
		<li><a href="<%= following_user_path(@user) %>"><span>关注:</span><strong id="following"><%= @user.following.count %></strong></a></li>
		<li><a href="<%= followers_user_path(@user) %>"><span>粉丝:</span><strong id="followers"><%= @user.followers.count %></strong></a></li>
	</ul>
<!--/个人信息--></div>

diode/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diode</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %>
  <%= stylesheet_link_tag params[:controller] %>

  <%= render :partial => "layouts/fav_touch" %>
  <%= csrf_meta_tags %>
</head>
<body>
   
<%= render :partial => "layouts/topbar" %>
<!-- layout file used for home page-->
<div class="container-fluid">
     <%= render :partial => "layouts/sidebar" %>

     <div class="content">
       <!-- Main hero unit for a primary marketing message or call to action -->
       <div class="hero-unit">
         <h1>Hello, world!</h1>
         <h4>Session</h4> <%= debug(session) %> <h4>Params</h4> <%= debug(params) %> 
         <%= yield %>
         <p><a class="btn primary large">Learn more &raquo;</a></p>
       </div>

       <!-- Example row of columns -->
       <div class="row">
         <div class="span5">
            <h2>24小时最热</h2>
            <% 5.times do%>
            <div class="row">
                <div class="span5">
                    <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
            </div>
            <hr>
            <%end%>
        </div>
        <div class="span6">
           <h2>本周最热</h2>
            <% 5.times do%>
            <div class="row">
            	<div class="span6">
                        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                       <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
            </div>
            <hr>
            <%end%>
         </div>
         <div class="span5">
           <h2>本月最热</h2>
           <% 5.times do%>
			<div class="row">
				<div class="span5">

           <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
           <p><a class="btn" href="#">View details &raquo;</a></p>
				</div>
			</div>
			<hr>
			<%end%>
         </div>
       </div>

       <hr>

       <!-- Example row of columns -->
       <div class="row">
         <div class="span6">
           <h2>Heading</h2>
           <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
           <p><a class="btn" href="#">View details &raquo;</a></p>
         </div>
         <div class="span5">
           <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
           <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
         <div class="span5">
           <h2>Heading</h2>
           <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
           <p><a class="btn" href="#">View details &raquo;</a></p>
         </div>
       </div>

     </div>
		<%= render :partial => "layouts/footer" %>
   </div>



</body>
</html>

diode/app/views/layouts/devise_user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diode</title>
  <%= stylesheet_link_tag    "application","devise_user" %>
  <%= javascript_include_tag "application" %>
  
  <%= render :partial => "layouts/fav_touch" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "layouts/topbar" %>
<!-- layout file used for devise user register & login etc-->
<div class="container">

      <div class="content">
        <div class="page-header">
          <h1>段子社区<small>千金难买一笑 ; )</small></h1>
        </div>
        <div class="row">
            <div class="span4">
                <h3>高质量段子分享社区</h3>
            </div>
            <div class="span10">
                <h2></h2>
                <%= yield %>
            </div>
        </div>
      </div>

      <%= render :partial => "layouts/footer" %>
    </div>
</body>
</html>

diode/app/views/layouts/settings.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diode</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %>
  <%= stylesheet_link_tag params[:controller] %>

  <%= render :partial => "layouts/fav_touch" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "layouts/topbar" %>
<!-- layout file used for user settings etc-->
<div class="container">

      <div class="content">
		<!-- >
        <div class="page-header">
          <h1>段子社区<small>千金难买一笑 ; )</small></h1>
        </div>
		-->
        <div class="row">
            <div class="span4 ">
                <div class="well">
			         <h5>个人资料</h5>
			         <ul>
			           <li><%= link_to '账号设置', settings_index_path %></li>
			           <li><%= link_to 'Link','http://www.google.com.hk' %></li>
			           <li><a href="#">Link</a></li>
			           <li><a href="#">Link</a></li>
			         </ul>
			         <h5>热门标签</h5>
			         <ul>
			           <li><a href="#">Link</a></li>
			           <li><a href="#">Link</a></li>
			           <li><a href="#">Link</a></li>
			           <li><a href="#">Link</a></li>
			           <li><a href="#">Link</a></li>
			           <li><a href="#">Link</a></li>
			         </ul>
			</div>
            </div>
            <div class="span10 fix-margin">
				<div class="ok">
                <%= yield %>
				</div>
            </div>
        </div>
      </div>

      <%= render :partial => "layouts/footer" %>

    </div>
</body>
</html>

diode/app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diode</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %>
  <%= stylesheet_link_tag params[:controller] %>

  <%= render :partial => "layouts/fav_touch" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => "layouts/topbar" %>
<%= render :partial => "layouts/flash", :object => flash %>
<!-- layout file used for view user or user home-->
<div class="container-fluid">
     <div class="sidebar">
       <div class="well">
		<%= render :partial => "layouts/user_stat" %>
		<%= render :partial => "layouts/follow_form" if user_signed_in? %>
       </div>
     </div>
     <div class="content">
       <%= yield%>
       <%= render :partial => "layouts/footer" %>
     </div>
   </div>
</body>
</html>