diode/config/routes.rb
Diode::Application.routes.draw do
  get "settings/index"

  get "settings/password"

  get "settings/iquit"

  resources :tags, :settings

  resources :jokes do
    resources :comments
  end
  
  devise_for :users

  get "home/index"
  root :to => 'home#index'
  match 'home/:user_id' => 'home#show', :as => :show
  match 'home/:user_id/jokes' => 'home#show_user_jokes', :as => :show_user_jokes
  
  resources :users do
      member do
        get :following, :followers
      end
  end
  
  resources :relationships, :only => [:create, :destroy]
    

end

diode/app/models/joke.rb
class Joke < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :tags
  
  default_scope :order => 'created_at DESC'
  
    # Return microposts from the users being followed by the given user.
    scope :from_users_followed_by, lambda { |user| followed_by(user) }

    private
      # Return an SQL condition for users followed by the given user.
      # We include the user's own id as well.
      def self.followed_by(user)
        # following_ids = user.following.map(&:id)
        #following_ids = user.following_ids
        following_ids = %(SELECT followed_id FROM relationships
                                WHERE follower_id = :user_id)
        where("user_id IN (#{following_ids}) OR user_id = :user_id",
              { :user_id => user })
      end
end

diode/app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  layout "users",:except=>[:rss,:atom,:json]
  
  # GET /jokes
  # GET /jokes.json
  def index
    @jokes = Joke.all
    flash[:notice] = '测试消息'
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @jokes }
    end
  end

  # GET /jokes/1
  # GET /jokes/1.json
  def show
    @joke = Joke.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @joke }
    end
  end

  # GET /jokes/new
  # GET /jokes/new.json
  def new
    @joke = Joke.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @joke }
    end
  end

  # GET /jokes/1/edit
  def edit
    @joke = Joke.find(params[:id])
  end

  # POST /jokes
  # POST /jokes.json
  def create
    @joke = Joke.new(params[:joke].except(:tags))
    str_tags = params[:joke][:tags].split(',')
    @tags = str_tags.map {|tag_name|
      Tag.find_or_create_by_name(tag_name)
    }
    @joke.user = current_user
    @joke.tags = @tags
    
    respond_to do |format|
      if @joke.save
        format.html { redirect_to @joke, :notice => 'Joke was successfully created.' }
        format.json { render :json => @joke, :status => :created, :location => @joke }
      else
        format.html { render :action => "new" }
        format.json { render :json => @joke.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jokes/1
  # PUT /jokes/1.json
  def update
    @joke = Joke.find(params[:id])

    respond_to do |format|
      str_tags = params[:joke][:tags].split(',')
      @tags = str_tags.map {|tag_name|
        Tag.find_or_create_by_name(tag_name)
      }
      @joke.tags = @tags
      
      if @joke.update_attributes(params[:joke].except(:tags))
        format.html { redirect_to @joke, :notice => 'Joke was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @joke.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jokes/1
  # DELETE /jokes/1.json
  def destroy
    @joke = Joke.find(params[:id])
    @joke.destroy

    respond_to do |format|
      format.html { redirect_to jokes_url,:notice => '成功删除该段子' }
      format.json { head :ok }
    end
  end
end

diode/app/helpers/jokes_helper.rb
module JokesHelper
end

diode/app/views/jokes/_form.html.erb
<%= form_for(@joke) do |f| %>
<fieldset>

  <% if @joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@joke.errors.count, "error") %> prohibited this joke from being saved:</h2>

      <ul>
      <% @joke.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="clearfix">
	  <%= f.label :title %>
	  <div class="input">
		<%= f.text_field :title,:class=>'xxlarge',:placeholder=>'可留空' %>
		<span class="help-block">
		</span>
	  </div>
	</div>
	<div class="clearfix">
	  <%= f.label :content %>
	  <div class="input">
		<%= f.text_area :content,:rows=>10,:class=>'xxlarge' %>
		<span class="help-block">
			请文明发言,珍惜个人ID
		</span>
	  </div>
	</div>
	<div class="clearfix">
	  <%= f.label :tags %>
	  <div class="input">
		<%= f.text_field :tags,:class=>'xxlarge',:value=>@joke.tags.map{|x| x.name}.join(','),:placeholder=>'可以输入以英文逗号分隔的标签（最多支持三个）' %>
		<span class="help-block">
		</span>
	  </div>
	</div>
	<div class="clearfix">
	    <div class="input"><%= f.check_box :disable_comments %> <span>禁止评论</span> </div>
	</div>
  <div class="actions">
    <%= f.submit "发布",:class=>"btn primary"%>
  </div>
<% end %>

diode/app/views/jokes/_joke.html.erb
<div class="row">
	<div class="span1" style="text-align:center">
		<%=link_to image_tag("http://placehold.it/48x48",:class=>"thumbnail"), joke.user%>	
		<a href="#"><%=h joke.user.email%></a>
	</div>
	<div class="span10">
		<h5><%= link_to h(joke.title), joke %></h5>
		<div class="joke_content">
			<%=h joke.content%>
		</div>
		<div class="joke_tagbar">
			<ul class="unstyled" style="float:left;">
				<li class="first"><span class="label notice">tag1</span></li>
				<li><span class="label notice">tag2</span></li>
				<li><span class="label notice">tag3</span></li>
			</ul>
		    <ul class="unstyled" style="float:right;">
				<li><span class="lable"　style="float:right;"><%=time_ago_in_words joke.created_at %></span></li>
			</ul>
			
			<div style="clear:both;"></div>
		</div>
		<div class="joke_menubar">
			<ul class="unstyled" style="float:left;">
				<li class="first"><%= link_to image_tag("btn/hands_up.png",:size=>"24x24",:class=>""), joke %></li>
				<li><%= link_to image_tag("btn/hands_down.png",:size=>"24x24",:class=>""), joke %></li>
				<li></li>
			</ul>
			<ul class="unstyled" style="float:right;">
				<li><%= link_to image_tag("btn/view.png",:size=>"24x24",:class=>""), joke %></li>
				<li><%= link_to image_tag("btn/edit.png",:size=>"24x24",:class=>""), edit_joke_path(joke) %></li>
				<li><%= link_to image_tag("btn/delete.png",:size=>"24x24",:class=>""), joke, :confirm => 'Are you sure?', :method => :delete %></li>
				<li><%= link_to image_tag("btn/fav.png",:size=>"24x24",:class=>""), joke %></li>
				<li><%= link_to image_tag("btn/comment.png",:size=>"24x24",:class=>""), joke_comments_path(joke), :remote=>true %></li>
			</ul>
			<div style="clear:both;"></div>
			
		</div>
	</div>
</div>
<div class="row">
	<hr>
</div>

diode/app/views/jokes/edit.html.erb
<h1>Editing joke</h1>

<%= render 'form' %>

<%= link_to 'Show', @joke %> |
<%= link_to 'Back', jokes_path %>

diode/app/views/jokes/index.html.erb
<h1>Listing jokes</h1>

<table>
  <tr>
	<th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jokes.each do |joke| %>
  <tr>
	<td><%=render(:partial=>'joke',:object=>joke) %></td>
    <td><%= link_to 'Show', joke %></td>
    <td><%= link_to 'Edit', edit_joke_path(joke) %></td>
    <td><%= link_to 'Destroy', joke, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Joke', new_joke_path %>

diode/app/views/jokes/new.html.erb
<h1>New joke</h1>

<%= render 'form' %>

<%= link_to 'Back', jokes_path %>

diode/app/views/jokes/show.html.erb
<p id="notice"><%= notice %></p>
<%=render(:partial=>'joke',:object=>@joke) %>
<div class="row comments" id="comments">
<%= render(:partial=>'comments/comment',:collection=>@joke.comments) %>
</div>

<div class="row form">
	<div class="form">
	<h2>Add a comment:</h2>
	<%= form_for([@joke, @joke.comments.build], :remote=>true) do |f| %>
	  <div class="clearfix">
	  <%= f.label :content %>
	    <div class="input">
		  <%= f.text_area :content,:rows=>10,:class=>'xxlarge' %>
		  <span class="help-block">
			请文明发言,珍惜个人ID
		  </span>
	    </div>
	  </div>
	  <div class="actions">
	    <%= f.submit "Submit",:class=>"btn primary" %>
	  </div>
	<% end %>
	</div>
</div>


<%= link_to 'Edit', edit_joke_path(@joke) %> |
<%= link_to 'Back', jokes_path %>