diode/config/routes.rb
Diode::Application.routes.draw do
  get "settings/index"

  get "settings/password"

  get "settings/iquit"

  resources :tags, :settings

  resources :jokes do
    resources :comments
  end
  
  devise_for :users

  get "home/index"
  root :to => 'home#index'
  match 'home/:user_id' => 'home#show', :as => :show
  match 'home/:user_id/jokes' => 'home#show_user_jokes', :as => :show_user_jokes
  
  resources :users do
      member do
        get :following, :followers
      end
  end
  
  resources :relationships, :only => [:create, :destroy]
    

end

diode/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :joke
end

diode/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  layout "users",:except=>[:rss,:atom,:json]
  
  respond_to :html,:xml,:json,:js
  
  def index
    @joke = Joke.find(params[:joke_id])
    @comments = @joke.comments.order(:created_at).page(params[:page])
    respond_with(@comments)
  end
  def create
    @joke = Joke.find(params[:joke_id])
    @comment = @joke.comments.create(params[:comment])
    respond_with(@joke)
  end
  def show
  end
  def new
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    
    @joke = Joke.find(params[:joke_id])
    respond_with(@joke)
  end
  
end

diode/app/helpers/comments_helper.rb
module CommentsHelper
end

diode/app/views/comments/_comment.html.erb
<%# 
  - available local variables
    comment:       the comment object
-%>
<div class="comment">
	<div class="user_info small">
		<%= comment.user.object_id %>
	</div>
	<div class="content">
		<p><%= comment.content %></p>
    </div>
	<div class="">
    <p><%= link_to 'Destroy', joke_comment_path(comment.joke,comment), :confirm => 'Are you sure?', :method => :delete %></p>
	</div>
</div>

diode/app/views/comments/create.js.erb
$("#comments").append("<%=raw escape_javascript(render(@comment)) %>");
//$("#comments_count span").text($("#comments .comment").length + "条评论");

diode/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<%= render(:partial=>'comment',:collection=>@comments) %>

<br />

<%= link_to 'New Joke Comment', new_joke_comment_path %>

diode/app/views/comments/index.js.erb
if($("#comments").css('display')=='none')
{
$("#comments").html("<%=raw escape_javascript(render(:partial=>'comment',:collection=>@comments)) %>");
//$("#comments_count span").text($("#comments .comment").length + "条评论");

//if($("#comments").css('display')=='none')
//{
//	$("#comments").css('display','block');
//}
//else
//{
//	$("#comments").css('display','none');
//}